execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:cut_sandstone"},{Slot:3b,id:"minecraft:cut_sandstone"},{Slot:4b,id:"minecraft:cut_sandstone"},{Slot:6b,id:"minecraft:cut_sandstone"},{Slot:7b,id:"minecraft:cut_sandstone"},{Slot:8b,id:"minecraft:cut_sandstone"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:sandstone_stairs",Count:1b,tag:{gm4_custom_crafters:{multiplier:4}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:acacia_planks"},{Slot:1b,id:"minecraft:acacia_planks"},{Slot:2b,id:"minecraft:acacia_planks"},{Slot:3b,id:"minecraft:acacia_planks"},{Slot:4b,id:"minecraft:acacia_planks"},{Slot:5b,id:"minecraft:acacia_planks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:acacia_trapdoor",Count:1b,tag:{gm4_custom_crafters:{multiplier:2}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:nether_bricks"},{Slot:3b,id:"minecraft:nether_bricks"},{Slot:4b,id:"minecraft:nether_bricks"},{Slot:6b,id:"minecraft:nether_bricks"},{Slot:7b,id:"minecraft:nether_bricks"},{Slot:8b,id:"minecraft:nether_bricks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:nether_brick_stairs",Count:1b,tag:{gm4_custom_crafters:{multiplier:4}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:red_sandstone"},{Slot:1b,id:"minecraft:red_sandstone"},{Slot:2b,id:"minecraft:red_sandstone"},{Slot:3b,id:"minecraft:red_sandstone"},{Slot:4b,id:"minecraft:red_sandstone"},{Slot:5b,id:"minecraft:red_sandstone"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:red_sandstone_wall",Count:1b,tag:{gm4_custom_crafters:{multiplier:6}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:red_sandstone"},{Slot:3b,id:"minecraft:red_sandstone"},{Slot:4b,id:"minecraft:red_sandstone"},{Slot:6b,id:"minecraft:red_sandstone"},{Slot:7b,id:"minecraft:red_sandstone"},{Slot:8b,id:"minecraft:red_sandstone"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:red_sandstone_stairs",Count:1b,tag:{gm4_custom_crafters:{multiplier:4}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:quartz_pillar"},{Slot:3b,id:"minecraft:quartz_pillar"},{Slot:4b,id:"minecraft:quartz_pillar"},{Slot:6b,id:"minecraft:quartz_pillar"},{Slot:7b,id:"minecraft:quartz_pillar"},{Slot:8b,id:"minecraft:quartz_pillar"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:quartz_stairs",Count:1b,tag:{gm4_custom_crafters:{multiplier:4}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:acacia_planks"},{Slot:3b,id:"minecraft:acacia_planks"},{Slot:4b,id:"minecraft:acacia_planks"},{Slot:6b,id:"minecraft:acacia_planks"},{Slot:7b,id:"minecraft:acacia_planks"},{Slot:8b,id:"minecraft:acacia_planks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:acacia_stairs",Count:1b,tag:{gm4_custom_crafters:{multiplier:4}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:smooth_quartz"},{Slot:3b,id:"minecraft:smooth_quartz"},{Slot:4b,id:"minecraft:smooth_quartz"},{Slot:6b,id:"minecraft:smooth_quartz"},{Slot:7b,id:"minecraft:smooth_quartz"},{Slot:8b,id:"minecraft:smooth_quartz"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:smooth_quartz_stairs",Count:1b,tag:{gm4_custom_crafters:{multiplier:4}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:spruce_planks"},{Slot:1b,id:"minecraft:spruce_planks"},{Slot:2b,id:"minecraft:spruce_planks"},{Slot:3b,id:"minecraft:spruce_planks"},{Slot:4b,id:"minecraft:spruce_planks"},{Slot:5b,id:"minecraft:spruce_planks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:spruce_trapdoor",Count:1b,tag:{gm4_custom_crafters:{multiplier:2}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:glass"},{Slot:1b,id:"minecraft:glass"},{Slot:2b,id:"minecraft:glass"},{Slot:3b,id:"minecraft:glass"},{Slot:4b,id:"minecraft:lime_dye"},{Slot:5b,id:"minecraft:glass"},{Slot:6b,id:"minecraft:glass"},{Slot:7b,id:"minecraft:glass"},{Slot:8b,id:"minecraft:glass"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:lime_stained_glass",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:glass"},{Slot:1b,id:"minecraft:glass"},{Slot:2b,id:"minecraft:glass"},{Slot:3b,id:"minecraft:glass"},{Slot:4b,id:"minecraft:cyan_dye"},{Slot:5b,id:"minecraft:glass"},{Slot:6b,id:"minecraft:glass"},{Slot:7b,id:"minecraft:glass"},{Slot:8b,id:"minecraft:glass"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:cyan_stained_glass",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:purpur_pillar"},{Slot:3b,id:"minecraft:purpur_pillar"},{Slot:4b,id:"minecraft:purpur_pillar"},{Slot:6b,id:"minecraft:purpur_pillar"},{Slot:7b,id:"minecraft:purpur_pillar"},{Slot:8b,id:"minecraft:purpur_pillar"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:purpur_stairs",Count:1b,tag:{gm4_custom_crafters:{multiplier:4}}}]}
scoreboard players set @s gm4_ac_craftsl 1
execute store result score blue_dye gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:blue_dye"}]
execute unless score blue_dye gm4_ac_count matches 1.. run scoreboard players set @s gm4_ac_craftsl 0
execute store result score sand gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:sand"}]
execute unless score sand gm4_ac_count matches 4.. run scoreboard players set @s gm4_ac_craftsl 0
execute store result score gravel gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:gravel"}]
execute unless score gravel gm4_ac_count matches 4.. run scoreboard players set @s gm4_ac_craftsl 0
execute if score @s gm4_ac_craftsl matches 1 run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:blue_concrete_powder",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}

execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:glass"},{Slot:1b,id:"minecraft:glass"},{Slot:2b,id:"minecraft:glass"},{Slot:3b,id:"minecraft:glass"},{Slot:4b,id:"minecraft:gray_dye"},{Slot:5b,id:"minecraft:glass"},{Slot:6b,id:"minecraft:glass"},{Slot:7b,id:"minecraft:glass"},{Slot:8b,id:"minecraft:glass"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:gray_stained_glass",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:acacia_planks"},{Slot:1b,id:"minecraft:acacia_planks"},{Slot:3b,id:"minecraft:acacia_planks"},{Slot:4b,id:"minecraft:acacia_planks"},{Slot:6b,id:"minecraft:acacia_planks"},{Slot:7b,id:"minecraft:acacia_planks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:acacia_door",Count:1b,tag:{gm4_custom_crafters:{multiplier:3}}}]}
scoreboard players set @s gm4_ac_craftsl 1
execute store result score gray_dye gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:gray_dye"}]
execute unless score gray_dye gm4_ac_count matches 1.. run scoreboard players set @s gm4_ac_craftsl 0
execute store result score sand gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:sand"}]
execute unless score sand gm4_ac_count matches 4.. run scoreboard players set @s gm4_ac_craftsl 0
execute store result score gravel gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:gravel"}]
execute unless score gravel gm4_ac_count matches 4.. run scoreboard players set @s gm4_ac_craftsl 0
execute if score @s gm4_ac_craftsl matches 1 run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:gray_concrete_powder",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}

execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:glass"},{Slot:1b,id:"minecraft:glass"},{Slot:2b,id:"minecraft:glass"},{Slot:3b,id:"minecraft:glass"},{Slot:4b,id:"minecraft:blue_dye"},{Slot:5b,id:"minecraft:glass"},{Slot:6b,id:"minecraft:glass"},{Slot:7b,id:"minecraft:glass"},{Slot:8b,id:"minecraft:glass"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:blue_stained_glass",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:jungle_planks"},{Slot:1b,id:"minecraft:jungle_planks"},{Slot:2b,id:"minecraft:jungle_planks"},{Slot:3b,id:"minecraft:jungle_planks"},{Slot:4b,id:"minecraft:jungle_planks"},{Slot:5b,id:"minecraft:jungle_planks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:jungle_trapdoor",Count:1b,tag:{gm4_custom_crafters:{multiplier:2}}}]}
scoreboard players set @s gm4_ac_craftsl 1
execute store result score cyan_dye gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:cyan_dye"}]
execute unless score cyan_dye gm4_ac_count matches 1.. run scoreboard players set @s gm4_ac_craftsl 0
execute store result score sand gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:sand"}]
execute unless score sand gm4_ac_count matches 4.. run scoreboard players set @s gm4_ac_craftsl 0
execute store result score gravel gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:gravel"}]
execute unless score gravel gm4_ac_count matches 4.. run scoreboard players set @s gm4_ac_craftsl 0
execute if score @s gm4_ac_craftsl matches 1 run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:cyan_concrete_powder",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}

execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:jungle_planks"},{Slot:3b,id:"minecraft:jungle_planks"},{Slot:4b,id:"minecraft:jungle_planks"},{Slot:6b,id:"minecraft:jungle_planks"},{Slot:7b,id:"minecraft:jungle_planks"},{Slot:8b,id:"minecraft:jungle_planks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:jungle_stairs",Count:1b,tag:{gm4_custom_crafters:{multiplier:4}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:nether_bricks"},{Slot:1b,id:"minecraft:nether_bricks"},{Slot:2b,id:"minecraft:nether_bricks"},{Slot:3b,id:"minecraft:nether_bricks"},{Slot:4b,id:"minecraft:nether_bricks"},{Slot:5b,id:"minecraft:nether_bricks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:nether_brick_wall",Count:1b,tag:{gm4_custom_crafters:{multiplier:6}}}]}
scoreboard players set @s gm4_ac_craftsl 1
execute store result score lime_dye gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:lime_dye"}]
execute unless score lime_dye gm4_ac_count matches 1.. run scoreboard players set @s gm4_ac_craftsl 0
execute store result score sand gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:sand"}]
execute unless score sand gm4_ac_count matches 4.. run scoreboard players set @s gm4_ac_craftsl 0
execute store result score gravel gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:gravel"}]
execute unless score gravel gm4_ac_count matches 4.. run scoreboard players set @s gm4_ac_craftsl 0
execute if score @s gm4_ac_craftsl matches 1 run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:lime_concrete_powder",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}

scoreboard players set @s gm4_ac_craftsl 1
execute store result score pink_dye gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:pink_dye"}]
execute unless score pink_dye gm4_ac_count matches 1.. run scoreboard players set @s gm4_ac_craftsl 0
execute store result score sand gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:sand"}]
execute unless score sand gm4_ac_count matches 4.. run scoreboard players set @s gm4_ac_craftsl 0
execute store result score gravel gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:gravel"}]
execute unless score gravel gm4_ac_count matches 4.. run scoreboard players set @s gm4_ac_craftsl 0
execute if score @s gm4_ac_craftsl matches 1 run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:pink_concrete_powder",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}

execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:jungle_planks"},{Slot:1b,id:"minecraft:jungle_planks"},{Slot:3b,id:"minecraft:jungle_planks"},{Slot:4b,id:"minecraft:jungle_planks"},{Slot:6b,id:"minecraft:jungle_planks"},{Slot:7b,id:"minecraft:jungle_planks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:jungle_door",Count:1b,tag:{gm4_custom_crafters:{multiplier:3}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:spruce_planks"},{Slot:1b,id:"minecraft:spruce_planks"},{Slot:3b,id:"minecraft:spruce_planks"},{Slot:4b,id:"minecraft:spruce_planks"},{Slot:6b,id:"minecraft:spruce_planks"},{Slot:7b,id:"minecraft:spruce_planks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:spruce_door",Count:1b,tag:{gm4_custom_crafters:{multiplier:3}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:glass"},{Slot:1b,id:"minecraft:glass"},{Slot:2b,id:"minecraft:glass"},{Slot:3b,id:"minecraft:glass"},{Slot:4b,id:"minecraft:pink_dye"},{Slot:5b,id:"minecraft:glass"},{Slot:6b,id:"minecraft:glass"},{Slot:7b,id:"minecraft:glass"},{Slot:8b,id:"minecraft:glass"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:pink_stained_glass",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:spruce_planks"},{Slot:3b,id:"minecraft:spruce_planks"},{Slot:4b,id:"minecraft:spruce_planks"},{Slot:6b,id:"minecraft:spruce_planks"},{Slot:7b,id:"minecraft:spruce_planks"},{Slot:8b,id:"minecraft:spruce_planks"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:spruce_stairs",Count:1b,tag:{gm4_custom_crafters:{multiplier:4}}}]}
