execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:glass_pane"},{Slot:1b,id:"minecraft:glass_pane"},{Slot:2b,id:"minecraft:glass_pane"},{Slot:3b,id:"minecraft:glass_pane"},{Slot:4b,id:"minecraft:orange_dye"},{Slot:5b,id:"minecraft:glass_pane"},{Slot:6b,id:"minecraft:glass_pane"},{Slot:7b,id:"minecraft:glass_pane"},{Slot:8b,id:"minecraft:glass_pane"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:orange_stained_glass_pane",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute store result score dried_kelp gm4_ac_count if data block ~ ~ ~ Items[{id:"minecraft:dried_kelp"}]
execute if score dried_kelp gm4_ac_count run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:dried_kelp_block",Count:1b,tag:{gm4_custom_crafters:{multiplier:1}}}]}

execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:glass_pane"},{Slot:1b,id:"minecraft:glass_pane"},{Slot:2b,id:"minecraft:glass_pane"},{Slot:3b,id:"minecraft:glass_pane"},{Slot:4b,id:"minecraft:yellow_dye"},{Slot:5b,id:"minecraft:glass_pane"},{Slot:6b,id:"minecraft:glass_pane"},{Slot:7b,id:"minecraft:glass_pane"},{Slot:8b,id:"minecraft:glass_pane"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:yellow_stained_glass_pane",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:glass_pane"},{Slot:1b,id:"minecraft:glass_pane"},{Slot:2b,id:"minecraft:glass_pane"},{Slot:3b,id:"minecraft:glass_pane"},{Slot:4b,id:"minecraft:purple_dye"},{Slot:5b,id:"minecraft:glass_pane"},{Slot:6b,id:"minecraft:glass_pane"},{Slot:7b,id:"minecraft:glass_pane"},{Slot:8b,id:"minecraft:glass_pane"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:purple_stained_glass_pane",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:iron_ingot"},{Slot:1b,id:"minecraft:iron_ingot"},{Slot:2b,id:"minecraft:iron_ingot"},{Slot:3b,id:"minecraft:iron_ingot"},{Slot:4b,id:"minecraft:iron_ingot"},{Slot:5b,id:"minecraft:iron_ingot"},{Slot:6b,id:"minecraft:iron_ingot"},{Slot:7b,id:"minecraft:iron_ingot"},{Slot:8b,id:"minecraft:iron_ingot"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:iron_block",Count:1b,tag:{gm4_custom_crafters:{multiplier:1}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:yellow_stained_glass"},{Slot:1b,id:"minecraft:yellow_stained_glass"},{Slot:2b,id:"minecraft:yellow_stained_glass"},{Slot:3b,id:"minecraft:yellow_stained_glass"},{Slot:4b,id:"minecraft:yellow_stained_glass"},{Slot:5b,id:"minecraft:yellow_stained_glass"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:yellow_stained_glass_pane",Count:1b,tag:{gm4_custom_crafters:{multiplier:16}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:smooth_red_sandstone"},{Slot:3b,id:"minecraft:smooth_red_sandstone"},{Slot:4b,id:"minecraft:smooth_red_sandstone"},{Slot:6b,id:"minecraft:smooth_red_sandstone"},{Slot:7b,id:"minecraft:smooth_red_sandstone"},{Slot:8b,id:"minecraft:smooth_red_sandstone"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:smooth_red_sandstone_stairs",Count:1b,tag:{gm4_custom_crafters:{multiplier:4}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:terracotta"},{Slot:1b,id:"minecraft:terracotta"},{Slot:2b,id:"minecraft:terracotta"},{Slot:3b,id:"minecraft:terracotta"},{Slot:4b,id:"minecraft:orange_dye"},{Slot:5b,id:"minecraft:terracotta"},{Slot:6b,id:"minecraft:terracotta"},{Slot:7b,id:"minecraft:terracotta"},{Slot:8b,id:"minecraft:terracotta"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:orange_terracotta",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:terracotta"},{Slot:1b,id:"minecraft:terracotta"},{Slot:2b,id:"minecraft:terracotta"},{Slot:3b,id:"minecraft:terracotta"},{Slot:4b,id:"minecraft:purple_dye"},{Slot:5b,id:"minecraft:terracotta"},{Slot:6b,id:"minecraft:terracotta"},{Slot:7b,id:"minecraft:terracotta"},{Slot:8b,id:"minecraft:terracotta"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:purple_terracotta",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:orange_stained_glass"},{Slot:1b,id:"minecraft:orange_stained_glass"},{Slot:2b,id:"minecraft:orange_stained_glass"},{Slot:3b,id:"minecraft:orange_stained_glass"},{Slot:4b,id:"minecraft:orange_stained_glass"},{Slot:5b,id:"minecraft:orange_stained_glass"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:orange_stained_glass_pane",Count:1b,tag:{gm4_custom_crafters:{multiplier:16}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:slime_ball"},{Slot:1b,id:"minecraft:slime_ball"},{Slot:2b,id:"minecraft:slime_ball"},{Slot:3b,id:"minecraft:slime_ball"},{Slot:4b,id:"minecraft:slime_ball"},{Slot:5b,id:"minecraft:slime_ball"},{Slot:6b,id:"minecraft:slime_ball"},{Slot:7b,id:"minecraft:slime_ball"},{Slot:8b,id:"minecraft:slime_ball"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:slime_block",Count:1b,tag:{gm4_custom_crafters:{multiplier:1}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:terracotta"},{Slot:1b,id:"minecraft:terracotta"},{Slot:2b,id:"minecraft:terracotta"},{Slot:3b,id:"minecraft:terracotta"},{Slot:4b,id:"minecraft:yellow_dye"},{Slot:5b,id:"minecraft:terracotta"},{Slot:6b,id:"minecraft:terracotta"},{Slot:7b,id:"minecraft:terracotta"},{Slot:8b,id:"minecraft:terracotta"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:yellow_terracotta",Count:1b,tag:{gm4_custom_crafters:{multiplier:8}}}]}
execute if score @s gm4_slot_count matches 6 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:purple_stained_glass"},{Slot:1b,id:"minecraft:purple_stained_glass"},{Slot:2b,id:"minecraft:purple_stained_glass"},{Slot:3b,id:"minecraft:purple_stained_glass"},{Slot:4b,id:"minecraft:purple_stained_glass"},{Slot:5b,id:"minecraft:purple_stained_glass"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:purple_stained_glass_pane",Count:1b,tag:{gm4_custom_crafters:{multiplier:16}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:gold_ingot"},{Slot:1b,id:"minecraft:gold_ingot"},{Slot:2b,id:"minecraft:gold_ingot"},{Slot:3b,id:"minecraft:gold_ingot"},{Slot:4b,id:"minecraft:gold_ingot"},{Slot:5b,id:"minecraft:gold_ingot"},{Slot:6b,id:"minecraft:gold_ingot"},{Slot:7b,id:"minecraft:gold_ingot"},{Slot:8b,id:"minecraft:gold_ingot"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:gold_block",Count:1b,tag:{gm4_custom_crafters:{multiplier:1}}}]}
execute if score @s gm4_slot_count matches 9 if block ~ ~ ~ dropper{Items:[{Slot:0b,id:"minecraft:packed_ice"},{Slot:1b,id:"minecraft:packed_ice"},{Slot:2b,id:"minecraft:packed_ice"},{Slot:3b,id:"minecraft:packed_ice"},{Slot:4b,id:"minecraft:packed_ice"},{Slot:5b,id:"minecraft:packed_ice"},{Slot:6b,id:"minecraft:packed_ice"},{Slot:7b,id:"minecraft:packed_ice"},{Slot:8b,id:"minecraft:packed_ice"}]} run data merge block ~ ~ ~ {Items:[{Slot:8b,id:"minecraft:blue_ice",Count:1b,tag:{gm4_custom_crafters:{multiplier:1}}}]}
